export const ACTION_TYPES = {
  SET_APPLICATION_DATA: "SET_APPLICATION_DATA",
  SET_USER: "SET_USER",
  ADD_CATEGORY: "ADD_CATEGORY",
  SHOW_CATEGORY_INPUT: "SHOW_CATEGORY_INPUT",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  SEARCH_CATEGORY: "SEARCH_CATEGORY",
  ADD_TASK: "ADD_TASK",
  OPEN_INFO_PANEL: "OPEN_INFO_PANEL",
  CLOSE_INFO_PANEL: "CLOSE_INFO_PANEL",
};
